### ISSUE TITLE
Error: Cannot find module '@graphprotocol/graph-cli/src/command-helpers/spinner'

### ISSUE THREAD

**Issue by moconnell** [graphprotocol/hardhat-graph#30]
When I add the  import in `hardhat.config.ts`, I get the following reference error:

```
An unexpected error occurred:
Error: Cannot find module '@graphprotocol/graph-cli/src/command-helpers/spinner'
Require stack:
- /foo/node_modules/@graphprotocol/hardhat-graph/dist/helpers/generator.js
- /foo/node_modules/@graphprotocol/hardhat-graph/dist/tasks.js
- /foo/node_modules/@graphprotocol/hardhat-graph/dist/index.js
- /foo/evm/hardhat.config.ts
- /foo/node_modules/hardhat/internal/core/config/config-loading.js
- /foo/node_modules/hardhat/internal/cli/cli.js
- /foo/node_modules/hardhat/internal/cli/bootstrap.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/foo/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/foo/node_modules/@graphprotocol/hardhat-graph/dist/helpers/generator.js:8:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Object.require.extensions.<computed> [as .js] (/foo/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/foo/node_modules/@graphprotocol/hardhat-graph/dist/helpers/generator.js',
    '/foo/node_modules/@graphprotocol/hardhat-graph/dist/tasks.js',
    '/foo/node_modules/@graphprotocol/hardhat-graph/dist/index.js',
    '/foo/evm/hardhat.config.ts',
    '/foo/node_modules/hardhat/internal/core/config/config-loading.js',
    '/foo/node_modules/hardhat/internal/cli/cli.js',
    '/foo/node_modules/hardhat/internal/cli/bootstrap.js'
  ]
}
error Command failed with exit code 1.
```

`project.json`:
```
  ...
  "dependencies": {
    "ts-node": "^10.9.1",
    "typechain": "^8.1.1",
    "typescript": "^5.0.4"
  },
  "devDependencies": {
    "@graphprotocol/graph-cli": "^0.49.0",
    "@graphprotocol/graph-ts": "^0.30.0",
    "@graphprotocol/hardhat-graph": "^0.1.0-alpha.2",
   ...
```

**Comment by dimitrovmaksim** [comment]
Install it from the github repo, the npm version is outdated

**Comment by moconnell** [comment]
GitHub version works like a charm thx
